/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;
import dominio.*;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class RegistroTematica extends javax.swing.JFrame {
    private Sistema sistema;
    /**
     * Creates new form RegistroTematica2
     */
    public RegistroTematica(Sistema unSistema) {
        sistema = unSistema;
        initComponents();
        this.setSize(600,350);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreTematica = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescripcionTematica = new javax.swing.JTextArea();
        btnCancelarTematica = new javax.swing.JButton();
        btnRegistrarTematica = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Registro de Temática");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Nombre:");

        txtNombreTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreTematicaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Descripción:");

        txtDescripcionTematica.setColumns(20);
        txtDescripcionTematica.setRows(5);
        jScrollPane2.setViewportView(txtDescripcionTematica);

        btnCancelarTematica.setText("Cancelar");
        btnCancelarTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTematicaActionPerformed(evt);
            }
        });

        btnRegistrarTematica.setText("Registrar");
        btnRegistrarTematica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarTematicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(btnCancelarTematica))
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnRegistrarTematica)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(txtNombreTematica, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNombreTematica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarTematica)
                    .addComponent(btnCancelarTematica))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 610, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreTematicaActionPerformed

    private void btnCancelarTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTematicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarTematicaActionPerformed

    private void btnRegistrarTematicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarTematicaActionPerformed
        String nombre = txtNombreTematica.getText();
        String descripcion = txtDescripcionTematica.getText();
        boolean existeTematica = sistema.agregarTematica(nombre, descripcion);
        
        if(nombre.trim().equals("") || descripcion.trim().equals("")) {
           JOptionPane.showMessageDialog(this, "Hay campos vacíos", "Error", JOptionPane.ERROR_MESSAGE);
        } else if(existeTematica) {
           JOptionPane.showMessageDialog(this, "Tematica ya existente", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
           JOptionPane.showMessageDialog(this, "Tematica creada", "OK", JOptionPane.INFORMATION_MESSAGE);
           txtDescripcionTematica.setText("");
           txtNombreTematica.setText("");
        }
        
    }//GEN-LAST:event_btnRegistrarTematicaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarTematica;
    private javax.swing.JButton btnRegistrarTematica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtDescripcionTematica;
    private javax.swing.JTextField txtNombreTematica;
    // End of variables declaration//GEN-END:variables
}
